version:              '3'
services:
    apache:
        build:        .docker/apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-available
          - .:/home/wwwroot
        depends_on:
          - php

    mysql:
        image:        mysql:5.7
        volumes:
            - .docker/data/db:/var/lib/mysql

    php:
        build:        .docker/php
        volumes:
          - .:/home/wwwroot
        depends_on:
          - mysql


    phpmyadmin:
        image:        phpmyadmin/phpmyadmin
        environment:
          PMA_HOST:   mysql
          PMA_PORT:   3306
        ports:
            - 8081:80
        links:
            - mysql

    blackfire:
        image:        blackfire/blackfire
