imports:
    - { resource:        config_dev.yml }

framework:
    test:                ~
    session:
        storage_id:      session.storage.mock_file
    profiler:
        collect:         false

web_profiler:
    toolbar:             false
    intercept_redirects: false

swiftmailer:
    disable_delivery:    true

security:
    firewalls:
        main:
            http_basic:  ~

parameters:
    database_host:       127.0.0.1
    database_port:       3306
    database_name:       todolist
    database_user:       root
    database_password:   ""
